modules-search: [ local, /usr/lib/calamares/modules ]
sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - packagechooser
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - networkcfg
      - users
      - displaymanager
      - initcpiocfg
      - bootloader
      - umount
branding: catarch
prompt-install: true
