backend: "yaml"
default: "Beginner"
choices:
  Beginner:
    label: "Beginner"
    packages:
      - catarch-profile-beginner
  Developer:
    label: "Developer"
    packages:
      - catarch-profile-developer
  Gamer:
    label: "Gamer"
    packages:
      - catarch-profile-gamer
  Creator:
    label: "Creator"
    packages:
      - catarch-profile-creator
